package com.ravindu2.movie;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * This class represents a Review entity.
 * It is mapped to a MongoDB collection named "reviews".
 */
@Document(collection = "reviews")  // Maps this class to the "reviews" collection in MongoDB
@Data  // Lombok annotation to generate standard methods such as getters, setters, toString, equals, and hashCode
@AllArgsConstructor  // Lombok annotation to generate a constructor with all fields as parameters
@NoArgsConstructor  // Lombok annotation to generate a no-argument constructor
public class Review {

    @Id  // Marks this field as the primary key in the MongoDB collection
    private ObjectId id;  // Unique identifier for the review, typically generated by MongoDB

    private String body;  // The text content of the review

    public Review(String body) {
        this.body = body;
    }
}
